function data = combine_across_blocks(field,results)
    data = {};
   if strcmp(field,'num_resp')
        data = vertcat(results{1,1}.results.number.num_resp,...
                        results{1,2}.results.number.num_resp,...
                        results{1,3}.results.number.num_resp,...
                        results{1,4}.results.number.num_resp,...
                        results{1,5}.results.number.num_resp,...
                        results{1,6}.results.number.num_resp,...
                        results{1,7}.results.number.num_resp,...
                        results{1,8}.results.number.num_resp,...
                        results{1,9}.results.number.num_resp);
   elseif strcmp(field,'num_RT')
        data = vertcat(results{1,1}.results.number.num_RT,...
                        results{1,2}.results.number.num_RT,...
                        results{1,3}.results.number.num_RT,...
                        results{1,4}.results.number.num_RT,...
                        results{1,5}.results.number.num_RT,...
                        results{1,6}.results.number.num_RT,...
                        results{1,7}.results.number.num_RT,...
                        results{1,8}.results.number.num_RT,...
                        results{1,9}.results.number.num_RT );
    elseif strcmp(field,'num_correct')
        data = vertcat(results{1,1}.results.number.correct,...
                        results{1,2}.results.number.correct,...
                        results{1,3}.results.number.correct,...
                        results{1,4}.results.number.correct,...
                        results{1,5}.results.number.correct,...
                        results{1,6}.results.number.correct,...
                        results{1,7}.results.number.correct,...
                        results{1,8}.results.number.correct,...
                        results{1,9}.results.number.correct);
    elseif strcmp(field,'dot_images')
        data = vertcat(results{1,1}.dot_stimuli_names{1,:},...
                        results{1,2}.dot_stimuli_names{1,:},...
                        results{1,3}.dot_stimuli_names{1,:},...
                        results{1,4}.dot_stimuli_names{1,:},...
                        results{1,5}.dot_stimuli_names{1,:},...
                        results{1,6}.dot_stimuli_names{1,:},...
                        results{1,7}.dot_stimuli_names{1,:},...
                        results{1,8}.dot_stimuli_names{1,:},...
                        results{1,9}.dot_stimuli_names{1,:});
    elseif strcmp(field,'arabic_response')
        data = vertcat(results{1,1}.results.arabic.response,...
                        results{1,2}.results.arabic.response,...
                        results{1,3}.results.arabic.response,...
                        results{1,4}.results.arabic.response,...
                        results{1,5}.results.arabic.response,...
                        results{1,6}.results.arabic.response,...
                        results{1,7}.results.arabic.response,...
                        results{1,8}.results.arabic.response,...
                        results{1,9}.results.arabic.response);
    elseif strcmp(field,'arabic_correct')
        data = vertcat(results{1,1}.results.arabic.correct,...
                        results{1,2}.results.arabic.correct,...
                        results{1,3}.results.arabic.correct,...
                        results{1,4}.results.arabic.correct,...
                        results{1,5}.results.arabic.correct,...
                        results{1,6}.results.arabic.correct,...
                        results{1,7}.results.arabic.correct,...
                        results{1,8}.results.arabic.correct,...
                        results{1,9}.results.arabic.correct);
   elseif strcmp(field,'arabic_RT')
        data = vertcat(results{1,1}.results.arabic.RT,...
                        results{1,2}.results.arabic.RT,...
                        results{1,3}.results.arabic.RT,...
                        results{1,4}.results.arabic.RT,...
                        results{1,5}.results.arabic.RT,...
                        results{1,6}.results.arabic.RT,...
                        results{1,7}.results.arabic.RT,...
                        results{1,8}.results.arabic.RT,...
                        results{1,9}.results.arabic.RT);
                    
                    
    else
        disp('field not recognised')
    end
end