function data = combine_across_blocks(field,results)
    data = {};
    if strcmp(field,'faces.detection')

        data = vertcat(results{1,1}.results.detection.faces.detection,...
                        results{1,2}.results.detection.faces.detection,...
                        results{1,3}.results.detection.faces.detection,...
                        results{1,4}.results.detection.faces.detection,...
                        results{1,5}.results.detection.faces.detection,...
                        results{1,6}.results.detection.faces.detection,...
                        results{1,7}.results.detection.faces.detection,...
                        results{1,8}.results.detection.faces.detection,...
                        results{1,9}.results.detection.faces.detection);
    elseif strcmp(field, 'houses.detection')
        data = vertcat(results{1,1}.results.detection.houses.detection,...
                        results{1,2}.results.detection.houses.detection,...
                        results{1,3}.results.detection.houses.detection,...
                        results{1,4}.results.detection.houses.detection,...
                        results{1,5}.results.detection.houses.detection,...
                        results{1,6}.results.detection.houses.detection,...
                        results{1,7}.results.detection.houses.detection,...
                        results{1,8}.results.detection.houses.detection,...
                        results{1,9}.results.detection.houses.detection);
    elseif strcmp(field,'faces.detection_RT')
         data = vertcat(results{1,1}.results.detection.faces.detection_RT,...
                        results{1,2}.results.detection.faces.detection_RT,...
                        results{1,3}.results.detection.faces.detection_RT,...
                        results{1,4}.results.detection.faces.detection_RT,...
                        results{1,5}.results.detection.faces.detection_RT,...
                        results{1,6}.results.detection.faces.detection_RT,...
                        results{1,7}.results.detection.faces.detection_RT,...
                        results{1,8}.results.detection.faces.detection_RT,...
                        results{1,9}.results.detection.faces.detection_RT);
    elseif strcmp(field,'houses.detection_RT')
        data = vertcat(results{1,1}.results.detection.houses.detection_RT,...
                        results{1,2}.results.detection.houses.detection_RT,...
                        results{1,3}.results.detection.houses.detection_RT,...
                        results{1,4}.results.detection.houses.detection_RT,...
                        results{1,5}.results.detection.houses.detection_RT,...
                        results{1,6}.results.detection.houses.detection_RT,...
                        results{1,7}.results.detection.houses.detection_RT,...
                        results{1,8}.results.detection.houses.detection_RT,...
                        results{1,9}.results.detection.houses.detection_RT);
        
    elseif strcmp(field,'faces.correct')
        data = vertcat(results{1,1}.results.detection.faces.correct,...
                        results{1,2}.results.detection.faces.correct,...
                        results{1,3}.results.detection.faces.correct,...
                        results{1,4}.results.detection.faces.correct,...
                        results{1,5}.results.detection.faces.correct,...
                        results{1,6}.results.detection.faces.correct,...
                        results{1,7}.results.detection.faces.correct,...
                        results{1,8}.results.detection.faces.correct,...
                        results{1,9}.results.detection.faces.correct);
    elseif strcmp(field,'houses.correct')
        data = vertcat(results{1,1}.results.detection.houses.correct,...
                        results{1,2}.results.detection.houses.correct,...
                        results{1,3}.results.detection.houses.correct,...
                        results{1,4}.results.detection.houses.correct,...
                        results{1,5}.results.detection.houses.correct,...
                        results{1,6}.results.detection.houses.correct,...
                        results{1,7}.results.detection.houses.correct,...
                        results{1,8}.results.detection.houses.correct,...
                        results{1,9}.results.detection.houses.correct);
    elseif strcmp(field,'faces.confidence')
        data = vertcat(results{1,1}.results.detection.faces.confidence,...
                        results{1,2}.results.detection.faces.confidence,...
                        results{1,3}.results.detection.faces.confidence,...
                        results{1,4}.results.detection.faces.confidence,...
                        results{1,5}.results.detection.faces.confidence,...
                        results{1,6}.results.detection.faces.confidence,...
                        results{1,7}.results.detection.faces.confidence,...
                        results{1,8}.results.detection.faces.confidence,...
                        results{1,9}.results.detection.faces.confidence);
    elseif strcmp(field,'houses.confidence')
        data = vertcat(results{1,1}.results.detection.houses.confidence,...
                        results{1,2}.results.detection.houses.confidence,...
                        results{1,3}.results.detection.houses.confidence,...
                        results{1,4}.results.detection.houses.confidence,...
                        results{1,5}.results.detection.houses.confidence,...
                        results{1,6}.results.detection.houses.confidence,...
                        results{1,7}.results.detection.houses.confidence,...
                        results{1,8}.results.detection.houses.confidence,...
                        results{1,9}.results.detection.houses.confidence);
   

     elseif strcmp(field,'faces.confidence_RT')
        data = vertcat(results{1,1}.results.detection.faces.confidence_RT,...
                        results{1,2}.results.detection.faces.confidence_RT,...
                        results{1,3}.results.detection.faces.confidence_RT,...
                        results{1,4}.results.detection.faces.confidence_RT,...
                        results{1,5}.results.detection.faces.confidence_RT,...
                        results{1,6}.results.detection.faces.confidence_RT,...
                        results{1,7}.results.detection.faces.confidence_RT,...
                        results{1,8}.results.detection.faces.confidence_RT,...
                        results{1,9}.results.detection.faces.confidence_RT);
    elseif strcmp(field,'houses.confidence_RT')
        data = vertcat(results{1,1}.results.detection.houses.confidence_RT,...
                        results{1,2}.results.detection.houses.confidence_RT,...
                        results{1,3}.results.detection.houses.confidence_RT,...
                        results{1,4}.results.detection.houses.confidence_RT,...
                        results{1,5}.results.detection.houses.confidence_RT,...
                        results{1,6}.results.detection.houses.confidence_RT,...
                        results{1,7}.results.detection.houses.confidence_RT,...
                        results{1,8}.results.detection.houses.confidence_RT,...
                        results{1,9}.results.detection.houses.confidence_RT);
    elseif strcmp(field,'num_resp')
        data = vertcat(results{1,1}.results.number.num_resp,...
                        results{1,2}.results.number.num_resp,...
                        results{1,3}.results.number.num_resp,...
                        results{1,4}.results.number.num_resp,...
                        results{1,5}.results.number.num_resp,...
                        results{1,6}.results.number.num_resp,...
                        results{1,7}.results.number.num_resp,...
                        results{1,8}.results.number.num_resp,...
                        results{1,9}.results.number.num_resp);
   elseif strcmp(field,'num_RT')
        data = vertcat(results{1,1}.results.number.num_RT,...
                        results{1,2}.results.number.num_RT,...
                        results{1,3}.results.number.num_RT,...
                        results{1,4}.results.number.num_RT,...
                        results{1,5}.results.number.num_RT,...
                        results{1,6}.results.number.num_RT,...
                        results{1,7}.results.number.num_RT,...
                        results{1,8}.results.number.num_RT,...
                        results{1,9}.results.number.num_RT );
    elseif strcmp(field,'num_correct')
        data = vertcat(results{1,1}.results.number.correct,...
                        results{1,2}.results.number.correct,...
                        results{1,3}.results.number.correct,...
                        results{1,4}.results.number.correct,...
                        results{1,5}.results.number.correct,...
                        results{1,6}.results.number.correct,...
                        results{1,7}.results.number.correct,...
                        results{1,8}.results.number.correct,...
                        results{1,9}.results.number.correct);
    elseif strcmp(field,'dot_images')
        data = vertcat(results{1,1}.dot_stimuli_names{1,:},...
                        results{1,2}.dot_stimuli_names{1,:},...
                        results{1,3}.dot_stimuli_names{1,:},...
                        results{1,4}.dot_stimuli_names{1,:},...
                        results{1,5}.dot_stimuli_names{1,:},...
                        results{1,6}.dot_stimuli_names{1,:},...
                        results{1,7}.dot_stimuli_names{1,:},...
                        results{1,8}.dot_stimuli_names{1,:},...
                        results{1,9}.dot_stimuli_names{1,:});
                    
    else
        disp('field not recognised')
    end
end